upd
Anna-K-S/mi_app_flutter pull request #1
Opened 2023-03-08 00:49 UTC by Anna-K-S

@feduke-nukem

2023-03-08 07:23 UTC, feduke-nukem requested changes

2023-03-08 07:23 UTC, feduke-nukem commented on lib/main.dart
>                Row(children: <Widget>[
Стоит убрать `Row` и оставить просто `Container`

2023-03-09 22:19 UTC, Anna-K-S commented on lib/main.dart
>                Row(children: <Widget>[
сделано

2023-03-09 22:21 UTC, Anna-K-S commented on lib/main.dart
>                Row(children: <Widget>[
сделано

2023-03-10 02:37 UTC, merged